'use client';

import { SpotifyTrack, spotify } from '@/lib/spotify';
import Image from 'next/image';
import { useState } from 'react';

interface GeneratedPlaylistProps {
  playlistName: string;
  tracks: SpotifyTrack[];
  userId: string;
  onClear: () => void;
}

export const GeneratedPlaylist: React.FC<GeneratedPlaylistProps> = ({ playlistName, tracks, userId, onClear }) => {
  const [isSaving, setIsSaving] = useState(false);
  const [isSaved, setIsSaved] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleSavePlaylist = async () => {
    setIsSaving(true);
    setError(null);
    try {
      const newPlaylist = await spotify.createPlaylist(userId, playlistName, `Generated by AI Mood DJ for the mood: ${playlistName}`);
      const trackUris = tracks.map(track => track.uri);
      await spotify.addTracksToPlaylist(newPlaylist.id, trackUris);
      setIsSaved(true);
    } catch (err) {
      console.error("Failed to save playlist:", err);
      setError("Oops! Couldn't save the playlist. Please try again.");
    } finally {
      setIsSaving(false);
    }
  };

  if (isSaved) {
    return (
      <div className="bg-gray-800/50 backdrop-blur-sm rounded-xl p-6 border border-green-500/50 text-center">
        <h3 className="text-2xl font-bold text-white mb-2">Playlist Saved! ✅</h3>
        <p className="text-green-200 mb-4">&quot;{playlistName}&quot; is now in your Spotify library.</p>
        <button
          onClick={onClear}
          className="bg-gray-700 hover:bg-gray-600 text-white px-6 py-2 rounded-full transition-colors"
        >
          Create Another
        </button>
      </div>
    );
  }

  return (
    <div className="bg-gray-800/50 backdrop-blur-sm rounded-xl p-6 border border-gray-700/50">
      <div className="flex items-center justify-between mb-4">
        <div>
          <h2 className="text-2xl font-bold text-white">{playlistName}</h2>
          <p className="text-gray-300">{tracks.length} tracks curated for you</p>
        </div>
        <button onClick={onClear} className="text-gray-400 hover:text-white">&times; Clear</button>
      </div>
      
      <div className="max-h-96 overflow-y-auto space-y-2 pr-2 mb-4">
        {tracks.map((track) => (
          <div key={track.id} className="flex items-center space-x-3 bg-gray-900/50 p-2 rounded-md">
            <div className="w-10 h-10 rounded bg-gray-700 relative flex-shrink-0">
              {track.album.images?.[0] && (
                <Image src={track.album.images[0].url} alt={track.album.name} fill sizes="40px" className="rounded object-cover" />
              )}
            </div>
            <div className="flex-1 min-w-0">
              <p className="text-white text-sm truncate">{track.name}</p>
              <p className="text-gray-400 text-xs truncate">{track.artists.map(a => a.name).join(', ')}</p>
            </div>
          </div>
        ))}
      </div>

      {error && <p className="text-red-400 text-center text-sm mb-3">{error}</p>}

      <button
        onClick={handleSavePlaylist}
        disabled={isSaving}
        className="w-full bg-green-600 hover:bg-green-700 disabled:bg-gray-600 text-white px-4 py-3 rounded-full transition-all duration-200 font-bold flex items-center justify-center space-x-2"
      >
        {isSaving ? (
          <>
            <div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
            <span>Saving to Spotify...</span>
          </>
        ) : (
          <span>Save to Spotify</span>
        )}
      </button>
    </div>
  );
};