"use client";

import Image from 'next/image';
import { SpotifyPlaylist, SpotifyTrack } from '@/lib/spotify';

interface PlaylistPosterProps {
  playlist: SpotifyPlaylist;
  tracks: SpotifyTrack[];
  onClose: () => void;
}

export default function PlaylistPoster({ playlist, tracks, onClose }: PlaylistPosterProps) {
  if (!playlist) return null;

  const topTracks = tracks.slice(0, 10); // Get top 10 tracks for the poster

  return (
    <div 
      className="fixed inset-0 bg-black bg-opacity-80 flex items-center justify-center z-50 p-4"
      onClick={onClose}
    >
      <div 
        className="relative bg-gray-900 rounded-lg shadow-2xl w-full max-w-md mx-auto overflow-hidden border-4 border-green-500"
        onClick={(e) => e.stopPropagation()} // Prevent closing when clicking inside the poster
      >
        {/* Background Image */}
        {playlist.images?.[0]?.url && (
          <Image
            src={playlist.images[0].url}
            alt={`${playlist.name} background`}
            layout="fill"
            objectFit="cover"
            className="opacity-20 blur-sm"
          />
        )}

        <div className="relative p-8 text-white text-center">
          {/* Close Button */}
          <button 
            onClick={onClose}
            className="absolute top-4 right-4 bg-black bg-opacity-50 rounded-full p-2 hover:bg-opacity-75 transition-colors"
          >
            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>

          {/* Main Playlist Image */}
          {playlist.images?.[0]?.url && (
            <div className="mb-6">
              <Image
                src={playlist.images[0].url}
                alt={playlist.name}
                width={200}
                height={200}
                className="rounded-lg shadow-lg mx-auto border-2 border-white"
              />
            </div>
          )}

          {/* Playlist Title */}
          <h2 className="text-4xl font-extrabold tracking-tight mb-4" style={{ textShadow: '2px 2px 4px rgba(0,0,0,0.7)' }}>
            {playlist.name}
          </h2>

          {/* Divider */}
          <div className="w-24 h-1 bg-green-500 mx-auto my-6 rounded"></div>

          {/* Track List */}
          <div className="text-left max-h-60 overflow-y-auto pr-2">
            <ul className="space-y-2">
              {topTracks.map((track, index) => (
                <li key={track.id + index} className="flex items-center space-x-3">
                  <span className="font-mono text-green-400 w-6">{index + 1}.</span>
                  <div>
                    <p className="font-semibold truncate">{track.name}</p>
                    <p className="text-sm text-gray-400 truncate">{track.artists.map(a => a.name).join(', ')}</p>
                  </div>
                </li>
              ))}
            </ul>
          </div>

          {/* Footer */}
          <p className="mt-8 text-sm text-gray-500">
            Generated by Music Mood Maestro 🎵
          </p>
        </div>
      </div>
    </div>
  );
}