// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://jykbnnmvjpwmoxxhijgn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5a2Jubm12anB3bW94eGhpamduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NjExMDYsImV4cCI6MjA3MjQzNzEwNn0.tMyg7JSIuEBkBf4pJZFAkReo9hPnBsxz-fKMfyW7w0Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);